name: Cache List
on:
  workflow_dispatch:

env:
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.event.repository.name }}
  GH_TOKEN: ${{ github.token }}

jobs:
  cache:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: List caches
      #  id: list-caches
      #  shell: bash
      #  env:
      #     GH_TOKEN: ${{ inputs.github-token }}
      #     PAGE_SIZE: ${{ inputs.page-size }}
      #  run: |

      - name: Get the caches
        id: list-caches
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          function list_caches {
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$OWNER/$REPO/actions/caches
          } 
          pageindex=1
          echo "fetching page ${pageindex}..."
          first="$(list_caches "${pageindex}")"
          total_count="$(jq -r '.total_count' <<< "${first}")"
          all_ids="$(jq '.actions_caches[].id' <<< "${first}" | tr '\n' ' ')"
          echo "cache ids total: ${all_ids}"
          echo "cache_ids=$all_ids" >> "$GITHUB_OUTPUT"
