name: Cache List
on:
  workflow_dispatch:

env:
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.event.repository.name }}
  GH_TOKEN: ${{ github.token }}

jobs:
  cache:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Get
        id: cache-list
        run: |
          cacheList="$(gh api \
          -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/$OWNER/$REPO/actions/caches)"

          echo '::set-output name=CACHE_LIST::cacheList'

      - name: echo command
        run: echo 'Owner' = $OWNER 'Repo' $REPO 'GH_TOKEN'= $GH_TOKEN

      - name: Print Actions Cache
        run: echo "${{steps.cache-list.outputs.CACHE_LIST}}"

      # - name: Loop the array
      #   run: |
      #     for item in "${cacheList[@]}"; do
      #     name=$(echo "$item" | jq -r '.name')
      #     age=$(echo "$item" | jq -r '.age')
      #     # Check if the name contains "a"
      #     if [[ "$name" == *"a"* ]]; then
      #       echo "Name contains 'a': $name"
      #     else
      #       echo "Name does not contain 'a': $name"
      #     fi done
