name: 'Hashing the folder'

on:
  workflow_dispatch:

jobs:
  hash:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Hash the folder
        uses: theowenyoung/folder-hash@v3
        id: hashing
        with:
          path: |
            ios/fastlane

      - name: Output the hash folder value
        run: echo ${{steps.hashing.outputs.hash}}

      - name: Setup yarn and caching dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install all dependencies
        run: yarn install --immutable

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.7'

      - name: Cache Pods
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: cache-${{ runner.os }}-pods-${{steps.hashing.outputs.hash }}

      - name: Install cocoapods
        run: |
          cd ios
          pod install
